---
- name: Install Rust
  shell: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    executable: /bin/bash
  become: false

- name: Source cargo environment
  shell: . "{{ user_home }}/.cargo/env"
  become: false
