---
- name: Add Microsoft GPG key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.gpg

- name: Add VSCode repository
  template:
    src: vscode.list.j2
    dest: /etc/apt/sources.list.d/vscode.list

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install VSCode
  apt:
    name: code
    state: present

- name: Set VSCode as default editor
  alternatives:
    name: editor
    path: /usr/bin/code
