---
- name: "Ensure /etc/apt/keyrings exists"
  file:
    path: /etc/apt/keyrings
    state: directory
  become: yes

- name: "Add Docker GPG key"
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
  become: yes

- name: "Add Docker repo"
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  become: yes

- name: "Update apt cache after Docker repo"
  apt:
    update_cache: yes
  become: yes

- name: "Install Docker packages"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: yes
