---
- name: Set GNOME favorites
  become: false
  command: >
    gsettings set org.gnome.shell favorite-apps
    "['org.gnome.Nautilus.desktop', 'snap-store_ubuntu-software.desktop',
    'org.gnome.Terminal.desktop', 'google-chrome.desktop', 'org.keepassxc.KeePassXC.desktop',
    'spotify.desktop', 'discord.desktop', 'steam.desktop', 'code.desktop',
    'cockos-reaper.desktop', 'org.rncbc.qjackctl.desktop',
    'wine-Programs-Guitar Pro 7-Guitar Pro 7.desktop']"
