---
- name: "Add KeePassXC PPA"
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present
  become: yes

- name: "Install KeePassXC"
  apt:
    name: keepassxc
    state: present
  become: yes
