---
- name: Enable i386 architecture
  command: dpkg --add-architecture i386

- name: Update apt
  apt:
    update_cache: yes

- name: Install Wine and Winetricks
  apt:
    name:
      - wine32:i386
      - wine64
      - winetricks
    state: present
