---
- name: "Download Google Chrome"
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: "{{ ansible_env.HOME }}/google-chrome.deb"

- name: "Install Google Chrome"
  apt:
    deb: "{{ ansible_env.HOME }}/google-chrome.deb"
  become: yes
