---
- name: Download Google Chrome
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: "{{ user_home }}/google-chrome.deb"

- name: Install Google Chrome
  apt:
    deb: "{{ user_home }}/google-chrome.deb"
