---
- name: "Update apt cache"
  apt:
    update_cache: yes
  become: yes

- name: "Upgrade system"
  apt:
    upgrade: dist
    yes: true
  become: yes

- name: "Install base packages"
  apt:
    name:
      - wget
      - git
      - curl
      - gpg
      - ca-certificates
      - gnupg
      - lsb-release
      - build-essential
      - libssl-dev
      - libffi-dev
      - libncurses5-dev
      - zlib1g
      - zlib1g-dev
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - make
      - gcc
      - liblzma-dev
      - nano
      - software-properties-common
      - zenity
      - libc++1
      - libgconf-2-4
      - htop
      - unzip
    state: present
  become: yes
