---
- name: Add Spotify GPG key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present

- name: Add Spotify repo
  copy:
    dest: /etc/apt/sources.list.d/spotify.list
    content: "deb http://repository.spotify.com stable non-free"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Spotify
  apt:
    name: spotify-client
    state: present
